name: CI tests

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        versions:
          - ghc: '8.10'
            cabal: '3.2'
          - ghc: '9.0'
            cabal: '3.4'
          - ghc: '9.2'
            cabal: '3.6'
          - ghc: '9.4'
            cabal: 'latest'
          - ghc: '9.6'
            cabal: 'latest'
    steps:
    - uses: actions/checkout@v1
    - name: Install cabal/ghc
      run: |
        ghcup install ghc --set ${{ matrix.versions.ghc }}
        ghcup install cabal --set ${{ matrix.versions.cabal }}

    - name: Cache cabal global package db
      id:   cabal-global
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-${{ matrix.versions.cabal }}-cabal-global-${{ secrets.CACHE_VERSION }}

    - name: Update
      run: |
          cabal v2-update
    - name: Build
      run: |
          cabal v2-build --enable-tests --disable-optimization -fexecutable
    - name: Test
      run: |
          cabal v2-test --disable-optimization

